INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Mango','Spring');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Strawberry','Spring');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Orange','Winter');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Lemon','Winter');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Blueberry','Summer');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Banana','Summer');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Watermelon','Summer');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Apple','Fall');
INSERT INTO Todo(id,name,task) VALUES (nextval('hibernate_sequence'),'Pear','Fall');