apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gxo
  namespace: openshift-gitops
spec:
  project: gxo
  source:
    repoURL: https://github.com/feven-redhat/statefull-basic-app.git
    targetRevision: master
    path: gitops/base
  destination:
    server: https://kubernetes.default.svc
    namespace: gxo
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
